-- ============================================
-- CaBa - Supabase Database Setup
-- Run this in your Supabase SQL Editor
-- ============================================

-- Step 1: Create the PYQs table
CREATE TABLE pyqs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject VARCHAR(100) NOT NULL,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  trick TEXT,
  trick_video_url TEXT,
  year INTEGER,
  exam_type VARCHAR(50),
  difficulty VARCHAR(20) DEFAULT 'Medium',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Step 2: Enable Row Level Security
ALTER TABLE pyqs ENABLE ROW LEVEL SECURITY;

-- Step 3: Create policies for public access
-- Anyone can read PYQs
CREATE POLICY "Public can read PYQs" ON pyqs
  FOR SELECT USING (true);

-- Only authenticated users can insert (you can change this)
CREATE POLICY "Authenticated users can insert PYQs" ON pyqs
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Step 4: Create indexes for better performance
CREATE INDEX idx_pyqs_subject ON pyqs(subject);
CREATE INDEX idx_pyqs_year ON pyqs(year);
CREATE INDEX idx_pyqs_exam_type ON pyqs(exam_type);

-- ============================================
-- Sample Data - Insert this to test your app
-- ============================================

INSERT INTO pyqs (subject, question, answer, trick, year, exam_type, difficulty) VALUES
-- Mathematics
(
  'Mathematics',
  'If sin θ + cos θ = √2, then find θ (0 ≤ θ ≤ π/2)',
  'θ = π/4',
  'Square both sides: (sin + cos)^2 = 2 → sin² + cos² + 2sin cos = 2 → 1 + sin 2θ = 2 → sin 2θ = 1 → 2θ = π/2 → θ = π/4',
  2024,
  'JEE Main',
  'Medium'
),
(
  'Mathematics',
  'Find the derivative of x² sin x',
  '2x sin x + x² cos x',
  'Use product rule: d(uv)/dx = u(dv/dx) + v(du/dx) = x²(cos x) + 2x(sin x)',
  2023,
  'JEE Main',
  'Easy'
),
(
  'Mathematics',
  'Solve: 2x + 5 = 15',
  'x = 5',
  'Subtract 5 from both sides: 2x = 10, then divide by 2: x = 5',
  2024,
  'JEE Main',
  'Easy'
),
(
  'Mathematics',
  'What is the square root of 144?',
  '12',
  '12 × 12 = 144. Remember squares of numbers 1-20!',
  2023,
  'JEE Main',
  'Easy'
),
(
  'Mathematics',
  'Find the value of 3³',
  '27',
  '3³ = 3 × 3 × 3 = 27. Cube means multiply by itself 3 times.',
  2022,
  'CBSE',
  'Easy'
),

-- Physics
(
  'Physics',
  'A body of mass 2kg is moving with velocity 3m/s. Find its kinetic energy.',
  'KE = 9 Joules',
  'Formula: KE = (1/2)mv² = (1/2)(2)(3)² = (1)(9) = 9 J',
  2024,
  'JEE Main',
  'Easy'
),
(
  'Physics',
  'The resistance of a wire at 20°C is 10Ω. Its resistance at 40°C is? (α = 0.002/°C)',
  '10.4 Ω',
  'Formula: R₂ = R₁[1 + α(T₂ - T₁)] = 10[1 + 0.002(20)] = 10[1.04] = 10.4 Ω',
  2022,
  'NEET',
  'Medium'
),
(
  'Physics',
  'Convert 100°F to Celsius',
  '37.8°C',
  'Formula: C = (F - 32) × 5/9 = (100 - 32) × 5/9 = 68 × 5/9 = 37.8°C',
  2023,
  'NEET',
  'Medium'
),
(
  'Physics',
  'What is the SI unit of force?',
  'Newton (N)',
  'Remember: 1N = 1kg × 1m/s². Named after Sir Isaac Newton.',
  2024,
  'JEE Main',
  'Easy'
),
(
  'Physics',
  'Calculate the force when mass = 10kg and acceleration = 5m/s²',
  '50 Newtons',
  'Formula: F = ma = 10 × 5 = 50 N',
  2024,
  'NEET',
  'Easy'
),

-- Chemistry
(
  'Chemistry',
  'The number of unpaired electrons in Mn²⁺ ion is? (Atomic number of Mn = 25)',
  '5 unpaired electrons',
  'Mn: [Ar] 3d⁵ 4s², Mn²⁺: [Ar] 3d⁵. All 5 d-electrons are unpaired (Hund rule)!',
  2023,
  'JEE Main',
  'Hard'
),
(
  'Chemistry',
  'The IUPAC name of [Co(NH₃)₆]Cl₃ is',
  'Hexaamminecobalt(III) chloride',
  '6 NH₃ = hexaammine, Co = cobalt, 3+ charge = Cobalt(III). Chloride for 3Cl⁻',
  2021,
  'JEE Main',
  'Medium'
),
(
  'Chemistry',
  'Find the molar mass of H₂SO₄',
  '98 g/mol',
  'H=1, S=32, O=16. H₂: 2×1=2, S:32, O₄: 4×16=64. Total: 2+32+64=98 g/mol',
  2024,
  'NEET',
  'Easy'
),
(
  'Chemistry',
  'What is the atomic number of Carbon?',
  '6',
  'Remember: C for Carbon, 6 electrons in neutral atom.',
  2023,
  'CBSE',
  'Easy'
),
(
  'Chemistry',
  'What is the pH of a neutral solution at 25°C?',
  '7',
  'Neutral means [H⁺] = [OH⁻] = 10⁻⁷. pH = -log(10⁻⁷) = 7',
  2022,
  'NEET',
  'Easy'
),

-- Biology
(
  'Biology',
  'Which hormone is known as the stress hormone?',
  'Cortisol',
  'Remember: CORTISOL = COPE + STRESS. Released by adrenal glands.',
  2022,
  'NEET',
  'Easy'
),
(
  'Biology',
  'What is the powerhouse of the cell?',
  'Mitochondria',
  'Remember "Mighty Mito"! Generates most ATP for the cell.',
  2024,
  'NEET',
  'Easy'
),
(
  'Biology',
  'How many bones are in the adult human body?',
  '206',
  'Adult has 206 bones. Remember with song or acronym for carpals/tarsals.',
  2023,
  'CBSE',
  'Easy'
),
(
  'Biology',
  'What is the largest organ in the human body?',
  'Skin',
  'The integumentary system - includes skin, hair, nails.',
  2024,
  'NEET',
  'Easy'
),
(
  'Biology',
  'Which blood group is known as universal donor?',
  'O negative (O⁻)',
  'O- has no A, B, or Rh antigens. Can be given to anyone.',
  2022,
  'NEET',
  'Medium'
),

-- English
(
  'English',
  'Fill in the blank: She _____ (come) to India last year.',
  'came',
  'Last year = Past tense. "Came" is already the past tense form.',
  2021,
  'CBSE',
  'Easy'
),
(
  'English',
  'Principal vs Principle - Which is correct? The school _____ was very strict.',
  'principal',
  'Remember: A principal is your "pal" at school (person). Principle is a rule.',
  2023,
  'CBSE',
  'Easy'
),
(
  'English',
  'Identify the noun: "Honesty is the best policy."',
  'Honesty',
  "Noun is a person, place, thing, or idea. Honesty is an abstract noun (idea).",
  2022,
  'CBSE',
  'Easy'
),
(
  'English',
  'Convert to passive: "Someone stole my bike."',
  'My bike was stolen.',
  'Object (my bike) becomes subject. Use "be" + past participle.',
  2024,
  'CBSE',
  'Medium'
),
(
  'English',
  'Find the synonym of "HAPPY"',
  'Joyful, Pleased, Content',
  'Happy means feeling/showing pleasure or contentment.',
  2023,
  'CBSE',
  'Easy'
);

-- ============================================
-- Verify the data
-- ============================================
SELECT COUNT(*) as total_questions FROM pyqs;
SELECT DISTINCT subject, COUNT(*) as count FROM pyqs GROUP BY subject;
